version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "12:00"
    timezone: "America/New_York"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "12:00"
    timezone: "America/New_York"
