version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "12:00"
    timezone: "America/New_York"
- package-ecosystem: nuget
  directory: "/"
  groups:
    polly:
      patterns:
        - Polly*
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: weekly
    day: thursday
    time: "12:00"
    timezone: "America/New_York"
